apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: rabbitmq-infisical-secrets
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: infisical-sync
    environment: prod
spec:
  hostAPI: https://infisical.prod.saoad.dk
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: rabbitmq-kcmj
        secretsPath: /
        envSlug: prod
      credentialsRef:
        secretName: infisical-secrets
        secretNamespace: argocd
  managedSecretReference:
    secretName: rabbitmq-infisical-secrets
    secretNamespace: rabbitmq
    #creationPolicy: "Owner"
