apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range tuple "definitions.json" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{- end }}