users:
  - name: guest
    password: guest
    tags:
      - administrator

vhosts:
  - name: /

permissions:
  - user: guest
    vhost: /
    configure: ".*"
    write: ".*"
    read: ".*"

exchanges:
  - name: my-exchange
    vhost: /
    type: topic
    durable: true
    auto_delete: false
    internal: false
  - name: my-direct-exchange
    vhost: /
    type: direct
    durable: true
    auto_delete: false
    internal: false
  - name: nazarii-exchange
    vhost: /
    type: topic
    durable: true
    auto_delete: false
    internal: false
  - name: BANGER
    vhost: /
    type: topic
    durable: true
    auto_delete: false
    internal: false
  - name: even-more-cool-exchange
    vhost: /
    type: topic
    durable: true
    auto_delete: false
    internal: false
  - name: cool-banger-thing
    vhost: /
    type: topic
    durable: true
    auto_delete: false
    internal: false
  - name: another-one-cool-banger-thing
    vhost: /
    type: topic
    durable: true
    auto_delete: false
    internal: false


queues:
  - name: my-queue
    vhost: /
    durable: true
    auto_delete: false

bindings:
  - source: my-exchange
    vhost: /
    destination: my-queue
    destination_type: queue
    routing_key: my.routing.key