app:
  replicas: 1
  environment: stage
  env:
    MATOMO_DATABASE_ADAPTER: "mysql"
    MATOMO_DATABASE_TABLES_PREFIX: "matomo_"
    PHP_MEMORY_LIMIT: "512M"
    PHP_LOG_ERRORS: "On"
    PHP_ERROR_LOG: "/dev/stderr"
    PHP_DISPLAY_ERRORS: "On"
    PHP_ERROR_REPORTING: "E_ALL"

service:
  type: NodePort
  port: 80
  nodePort: 30080  # Access on this port

infisical:
  enabled: true
  environment: "staging"

mariadb:
  enabled: true
  storageSize: 10Gi

archiving:
  enabled: true
  schedule: "5 * * * *"
  url: "http://matomo:80"  # Use internal service name instead